spring:
  datasource:
    url: jdbc:h2:mem:testdb

api:
  pageable: >
    SpringFox's API doesn't handle Pageables correctly. Here is the correct usage:\n\
    page: The page number to retrieve (default is page 0)\n\
    size: The size of the page (default is 20)\n\
    sort: <Optional> The field to sort on. To perform multiple sorts, use multiples of these attributes. \
    To specify descending order, add ',desc' to the sort field.\n\
    Example: http://localhost:8080/api?page=1&size=25&sort=name,desc
  updateAsPatch: Null fields will not be updated (left the same)
  common:
    createdBy: User who created this entry in the DB
    createdDate: Datetime this entry was created in the DB
    lastModifiedBy: User who last modified this entry in the DB
    lastModifiedDate: Datetime this entry was last modified in the DB
  user:
    id: The user's ID
    name: The user's display name
    pronouns: The user's preferred pronouns
    blurb: Summary of the user's achievements
    crownCount: The number of crowns the user has at signup
    discordId: The user's Discord ID. Expected to be in the format <discord-name>#<four-digit id>
    twitchId: The user's Twitch ID. Expected to be their Twitch username
    twitterId: The user's Twitter ID. Expected to be their Twitter handle (no @)
  tournament:
    id: The tournament's ID
    name: The tournament's name
    signUpStartDate: The date and time tournament sign-ups begin
    signUpEndDate: The date and time tournament sign-ups close
    startDate: The date and time the tournament begins
    endDate: The date and time the tournament ends
  team:
    id: The team's ID
    name: The team's name
    color: The team's color
    seed: The team's seed
    preferredRegion: The team's preferred game region
  teamMember:
    id: The team member's ID
    backup: Boolean indicating if this is a backup team member
  matchup:
    id: The matchup ID
    matchupOrder: The order of the matchup on the bracket
    teamOne: The first team competing (only present for first round)
    teamOneSeed: The seed of the first team
    teamTwo: The second team competing (only present for first round)
    teamTwoSeed: The seed of the second team
    previousMatchupTeamOne: The prior matchup, which determined team one (only present for later rounds)
    previousMatchupTeamTwo: The prior matchup, which determined team two (only present for later rounds)
    round: The round this occured in
    winner: The winner of this round
    startDate: The date and time this match started
    endDate: The date and time this match ended
